################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1.c \
C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_accelero.c \
C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_gyro.c \
C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_humidity.c \
C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_magneto.c \
C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_pressure.c \
C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_temperature.c 

OBJS += \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1.o \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_accelero.o \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_gyro.o \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_humidity.o \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_magneto.o \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_pressure.o \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_temperature.o 

C_DEPS += \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1.d \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_accelero.d \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_gyro.d \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_humidity.d \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_magneto.d \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_pressure.d \
./Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_temperature.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1.o: C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DUSART_PRINT_MSG -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -D__IKS01A1 -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Projects/Multi/Applications/MQTT_IBM/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/Common" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/hts221" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lis3mdl" -I../../../../../../../../Drivers/BSP/Components/lps25h -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps25hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/M24SR" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-IDW01M1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/lib_NDEF/inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTClient-C/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTPacket/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Porting" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps22hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm303agr" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_accelero.o: C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_accelero.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DUSART_PRINT_MSG -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -D__IKS01A1 -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Projects/Multi/Applications/MQTT_IBM/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/Common" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/hts221" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lis3mdl" -I../../../../../../../../Drivers/BSP/Components/lps25h -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps25hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/M24SR" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-IDW01M1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/lib_NDEF/inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTClient-C/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTPacket/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Porting" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps22hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm303agr" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_gyro.o: C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_gyro.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DUSART_PRINT_MSG -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -D__IKS01A1 -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Projects/Multi/Applications/MQTT_IBM/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/Common" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/hts221" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lis3mdl" -I../../../../../../../../Drivers/BSP/Components/lps25h -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps25hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/M24SR" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-IDW01M1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/lib_NDEF/inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTClient-C/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTPacket/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Porting" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps22hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm303agr" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_humidity.o: C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_humidity.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DUSART_PRINT_MSG -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -D__IKS01A1 -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Projects/Multi/Applications/MQTT_IBM/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/Common" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/hts221" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lis3mdl" -I../../../../../../../../Drivers/BSP/Components/lps25h -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps25hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/M24SR" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-IDW01M1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/lib_NDEF/inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTClient-C/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTPacket/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Porting" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps22hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm303agr" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_magneto.o: C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_magneto.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DUSART_PRINT_MSG -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -D__IKS01A1 -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Projects/Multi/Applications/MQTT_IBM/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/Common" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/hts221" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lis3mdl" -I../../../../../../../../Drivers/BSP/Components/lps25h -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps25hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/M24SR" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-IDW01M1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/lib_NDEF/inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTClient-C/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTPacket/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Porting" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps22hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm303agr" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_pressure.o: C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_pressure.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DUSART_PRINT_MSG -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -D__IKS01A1 -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Projects/Multi/Applications/MQTT_IBM/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/Common" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/hts221" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lis3mdl" -I../../../../../../../../Drivers/BSP/Components/lps25h -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps25hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/M24SR" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-IDW01M1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/lib_NDEF/inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTClient-C/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTPacket/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Porting" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps22hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm303agr" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_temperature.o: C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1/x_nucleo_iks01a1_temperature.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DUSART_PRINT_MSG -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -D__IKS01A1 -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Projects/Multi/Applications/MQTT_IBM/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/CMSIS/Include" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/Common" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/hts221" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lis3mdl" -I../../../../../../../../Drivers/BSP/Components/lps25h -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps25hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/M24SR" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X-NUCLEO-IDW01M1" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/lib_NDEF/inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Inc" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/ST/STM32_SPWF01SA/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTClient-C/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/MQTTPacket/src" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Utils" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Middlewares/Third_Parties/MQTT-Paho/Porting" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lps22hb" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/Components/lsm303agr" -I"C:/Users/SevyaMM/Pictures/STM32CubeFGunctionPackWatson/Drivers/BSP/X_NUCLEO_IKS01A1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


